Swallow NoClassDefFoundErrors when reflecting AppleCore_fertlize methods  * Band-aid for a problem that I'm not sure how fix properly (as Reika put it: "I suspect it is because client-side methods are not normally explicitly marked @SideOnly when the parent method is, as that is normally redundant.")  * Fixes #48